name: Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push app image
        run: |
          docker build -t ankush2642/app:latest ./app-dockerfiles/app
          docker push ankush2642/appppp:latest

      - name: Build and push database image
        run: |
          docker build -t ankush2642/db:latest ./app-dockerfiles/db
          docker push ankush2642/dbbbbb:latest